# Generated by Django 2.2.16 on 2020-09-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_category_guidebookpart_historyrecord_track_trackcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='duration',
            field=models.FloatField(default=0),
        ),
    ]
