# Generated by Django 2.2.16 on 2020-09-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200922_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='duration',
            field=models.FloatField(null=True),
        ),
    ]
