# Generated by Django 2.2.16 on 2020-09-22 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200922_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guidebookpart',
            old_name='track_id',
            new_name='track',
        ),
        migrations.RenameField(
            model_name='historyrecord',
            old_name='track_id',
            new_name='track',
        ),
        migrations.RenameField(
            model_name='historyrecord',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='trackcategory',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='trackcategory',
            old_name='track_id',
            new_name='track',
        ),
    ]
