# Generated by Django 2.2.16 on 2020-09-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200922_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='thumbnail',
            field=models.ImageField(default='default.jpg', upload_to='thumbnail/'),
        ),
    ]
