# Generated by Django 2.2.16 on 2020-09-25 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0009_track_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Favorites',
                'ordering': ('-created',),
            },
        ),
        migrations.RenameField(
            model_name='track',
            old_name='author',
            new_name='subtitle',
        ),
        migrations.AddField(
            model_name='category',
            name='thumbnail',
            field=models.ImageField(default='default.jpg', upload_to='category/thumbnail/'),
        ),
        migrations.AlterField(
            model_name='historyrecord',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='GuidebookPart',
        ),
        migrations.AddField(
            model_name='favorite',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='track_favorite', to='home.Track'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
