# Generated by Django 2.2.16 on 2020-09-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20200925_2200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='duration',
            new_name='track_duration',
        ),
        migrations.AddField(
            model_name='track',
            name='intro_duration',
            field=models.FloatField(default=0.0),
        ),
    ]
