# Generated by Django 2.2.16 on 2020-09-29 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0011_auto_20200925_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tracks_in_category', to='home.Category'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('track', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='historyrecord',
            unique_together={('track', 'user')},
        ),
    ]
