# Generated by Django 2.2.16 on 2020-11-04 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0014_historytransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_competition', to='home.Competition')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_sport', to='home.Sport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
