# Generated by Django 2.2.16 on 2020-11-04 08:13

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0015_competition_sport_userpreference'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpreference',
            options={'ordering': ('-created',), 'verbose_name_plural': 'User Preferences'},
        ),
        migrations.AddField(
            model_name='userpreference',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='userpreference',
            unique_together={('user', 'sport')},
        ),
    ]
