# Generated by Django 2.2.16 on 2020-11-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20201109_1117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quicklink',
            options={'ordering': ('-created',), 'verbose_name_plural': 'QuickLinks'},
        ),
        migrations.AddField(
            model_name='quicklink',
            name='track',
            field=models.FileField(default=123, upload_to='tracks/'),
            preserve_default=False,
        ),
    ]
