# Generated by Django 2.2.17 on 2020-12-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20201118_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
