# Generated by Django 2.2.17 on 2020-12-13 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0022_auto_20201213_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=244)),
                ('type', models.CharField(choices=[('CODE', 'CODE'), ('LICENCE', 'LICENCE')], default='CODE', max_length=225)),
                ('percentage_off', models.CharField(max_length=4)),
                ('expire_at', models.DateField(blank=True, null=True)),
                ('used_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='code_used_by_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
