# Generated by Django 2.2.17 on 2020-12-13 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='used_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='code_used_by_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
