# Generated by Django 2.2.17 on 2020-12-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20201213_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='valid_for_months',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('18', '18'), ('24', '24'), ('36', '36'), ('48', '48'), ('50', '50')], default='1', max_length=225),
        ),
    ]
