# Generated by Django 2.2.17 on 2020-12-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_code_valid_for_months'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='code',
            options={'verbose_name_plural': 'Codes'},
        ),
        migrations.AlterField(
            model_name='code',
            name='code',
            field=models.CharField(max_length=244, unique=True),
        ),
    ]
