# Generated by Django 2.2.17 on 2020-12-31 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_challenge_challengetasks_lastseen_selectedchallenge_team_teamchatmessage_teammembers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='code',
            field=models.CharField(blank=True, max_length=244, null=True, unique=True),
        ),
    ]
