# Generated by Django 2.2.17 on 2020-12-31 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_auto_20201231_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_team', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
