# Generated by Django 2.2.17 on 2021-01-01 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20201231_1602'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamchatmessage',
            options={'ordering': ('-created',), 'verbose_name_plural': 'Team Chat Messages'},
        ),
    ]
