# Generated by Django 2.2.17 on 2021-01-01 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_auto_20210101_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastseen',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='message_last_seen', to='home.TeamChatMessage'),
        ),
    ]
