# Generated by Django 2.2.17 on 2021-01-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_auto_20210101_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyrecord',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
