# Generated by Django 2.2.17 on 2021-01-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_historyrecord_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyrecord',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
