# Generated by Django 2.2.17 on 2021-01-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_auto_20210102_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyrecord',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
