# Generated by Django 2.2.17 on 2021-01-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_remove_historyrecord_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyrecord',
            name='last',
            field=models.DateField(auto_now=True),
        ),
    ]
