# Generated by Django 2.2.17 on 2021-01-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ('-order',), 'verbose_name_plural': 'Tracks'},
        ),
        migrations.AddField(
            model_name='category',
            name='small_thumbnail',
            field=models.ImageField(default='default.jpg', upload_to='category/thumbnail/'),
        ),
        migrations.AddField(
            model_name='track',
            name='artist',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
