# Generated by Django 2.2.18 on 2021-02-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_track_small_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='weeks',
            field=models.CharField(choices=[('4', '4'), ('8', '8'), ('12', '12')], default='4', max_length=225),
        ),
    ]
