# Generated by Django 2.2.18 on 2021-02-19 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0043_challenge_weeks'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachSurveyQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('0', 'First Time Log In'), ('1', 'Challenge End')], default='1', max_length=225)),
            ],
        ),
        migrations.AlterField(
            model_name='challengetasks',
            name='week',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='1', max_length=225),
        ),
        migrations.CreateModel(
            name='CoachSurveyAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(choices=[('1', 'Strongly Disagree'), ('2', 'Disagree'), ('3', 'Neutral'), ('4', 'Agree'), ('5', 'Strongly Agree')], max_length=225)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_answer', to='home.CoachSurveyQuestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_answer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
