# Generated by Django 2.2.18 on 2021-02-19 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_auto_20210219_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengetasks',
            name='print_and_provide',
            field=models.FileField(blank=True, null=True, upload_to='provide/'),
        ),
        migrations.AddField(
            model_name='challengetasks',
            name='type',
            field=models.TextField(choices=[('0', 'Listen Task'), ('1', 'Homework Taks'), ('2', 'Weekly Taks'), ('3', 'Print and provide'), ('4', 'Team Activity')], default='0', max_length=225),
        ),
    ]
