# Generated by Django 2.2.18 on 2021-02-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_auto_20210224_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='percentage_off',
        ),
        migrations.AlterField(
            model_name='code',
            name='code',
            field=models.CharField(blank=True, max_length=244, null=True, unique=True),
        ),
    ]
