# Generated by Django 2.2.18 on 2021-02-24 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_auto_20210224_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='code',
            old_name='valid_for_months',
            new_name='grant_premium_for_months',
        ),
    ]
