# Generated by Django 2.2.18 on 2021-03-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_auto_20210224_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='grant_premium_for_months',
        ),
        migrations.AddField(
            model_name='team',
            name='grant_premium_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
