# Generated by Django 2.2.19 on 2021-03-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_challengefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengefile',
            name='is_bulk',
            field=models.BooleanField(default=False),
        ),
    ]
