# Generated by Django 2.2.19 on 2021-04-05 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0053_code_users_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCodeUsed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='code_used_by_user', to='home.Code')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_custom_code', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
