# Generated by Django 2.2.19 on 2021-04-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0054_customcodeused'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengetasks',
            name='type',
            field=models.TextField(choices=[('0', 'Listen Task'), ('1', 'Homework Taks'), ('2', 'Weekly Taks'), ('3', 'Print and provide'), ('4', 'Team Activity'), ('5', 'Team Discussion')], default='0', max_length=225),
        ),
    ]
