# Generated by Django 2.2.19 on 2021-04-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0055_auto_20210420_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='grant_premium_for_months',
        ),
        migrations.AddField(
            model_name='code',
            name='grant_premium_for_days',
            field=models.IntegerField(default=1),
        ),
    ]
