import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  playingNow: {
    fontSize: 18,
    fontWeight: '600',
    fontStyle: 'normal',
    letterSpacing: 0,
    color: '#ffffff',
    textAlign: 'center',
  },
  topAreaContainer: {
    width: '100%',
    flex: 1,
    position: 'absolute',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'flex-start',
    height: '100%',
    paddingHorizontal: 10,
    paddingTop: 30,
  },
  titleText: {
    flex: 1,
    fontSize: 22,
    fontWeight: '600',
    fontStyle: 'italic',
    letterSpacing: 0,
    textAlign: 'center',
    color: '#0c0c0a',
  },
  subtitleText: {
    fontSize: 14,
    fontWeight: '500',
    fontStyle: 'italic',
    letterSpacing: 0,
    textAlign: 'center',
    color: '#90a0af',
    paddingLeft: 60,
    paddingRight: 60,
    marginBottom: 24,
  },
  sliderContainer: {
    width: '100%',
    paddingLeft: 24,
    paddingRight: 24,
  },
  slider: {
    flex: 1,
  },

  imageContainer: {
    backgroundColor: '#000',
    flex: 0.6,
    width: '100%',
    overflow: 'hidden',
  },
  image: {
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    width: '100%',
    overflow: 'hidden',
  },
  audioPoster: {
    flex: 1,
    width: '100%',
    height: '100%',
    overflow: 'hidden',
  },
  container: {
    flexDirection: 'column',
    alignItems: 'center',
    flex: 1,
    backgroundColor: '#fff',
  },
  controlsContainer: {
    flexDirection: 'column',
    alignItems: 'center',
    flex: 0.55,
    width: '100%',
  },
  controlButtons: {
    marginTop: 0,
    marginBottom: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-evenly',
  },
  playButton: {
    width: 90,
    height: 90,
    backgroundColor: '#e83a1f',
    borderColor: '#e83a1f',
    borderWidth: 0,
    paddingLeft: 0,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 45,
    marginHorizontal: 8,
  },
  titleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 16,
  },
  contButton: {
    height: 56,
    width: 48,
    flex: 0.5,
    marginHorizontal: 5,
  },
  button: {
    marginHorizontal: 4,
  },
  icon: {
    width: 48,
    height: 48,
  },

  header: {
    width: '100%',
    height: 50,
  },
  panelHeader: {
    alignItems: 'center',
  },
  panelHandle: {
    width: 40,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#00000040',
    marginBottom: 10,
  },
  panelTitle: {
    fontSize: 27,
    height: 35,
  },
  panelSubtitle: {
    fontSize: 14,
    color: 'gray',
    height: 30,
    marginBottom: 10,
  },

  upNextText: {
    fontSize: 14,
    fontWeight: '500',
    fontStyle: 'normal',
    letterSpacing: 0,
    marginLeft: 10,
    color: '#90a0af',
  },
  playIntroButton: {
    borderRadius: 4,
    borderStyle: 'solid',
    borderWidth: 2,
    borderColor: '#e83a1f',
    width: 250,
    height: 58,
    backgroundColor: 'white',
  },
  playIntroText: {
    fontSize: 18,
    fontWeight: 'bold',
    fontStyle: 'italic',
    lineHeight: 18,
    letterSpacing: -0.17,
    textAlign: 'center',
    color: '#e83a1f',
  },
  closeIntroButton: {
    margin: 8,
    position: 'absolute',
    opacity: 1,
    top: 5,
    right: 5,
    backgroundColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
  },
  banner: {
    backgroundColor: 'white',
    opacity: 1,
    padding: 40,
    alignItems: 'center',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    height: 130,
    width: '100%',
    left: -24,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 5,
    },
    shadowOpacity: 0.6,
    shadowRadius: 6,
    elevation: 10,
    position: 'absolute',
    bottom: 0,
    left: 0,
  },
  overlay: {
    position: 'absolute',
    height: '100%',
    width: '100%',
  },
});

export default styles;
