# Generated by Django 2.2.16 on 2020-09-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='competition',
            field=models.CharField(choices=[('0', 'Choose Competition Level'), ('1', 'High School'), ('2', 'College'), ('3', 'Professional'), ('4', 'Recreational'), ('5', 'Other')], default='0', max_length=225),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='users/images/'),
        ),
        migrations.AddField(
            model_name='user',
            name='sport',
            field=models.CharField(choices=[('0', 'Choose Sport Type'), ('1', 'Baseball'), ('2', 'Basketball'), ('3', 'Field Hockey'), ('4', 'Football'), ('5', 'Golf'), ('6', 'Gymnastics'), ('7', 'Hockey'), ('8', 'Lacrosse'), ('9', 'MMA'), ('10', 'Skiing'), ('11', 'Snowboarding'), ('12', 'Soccer'), ('13', 'Softball'), ('14', 'Swimming & Diving'), ('15', 'Tennis'), ('16', 'Track & Field'), ('17', 'Volleyball'), ('18', 'Water Polo'), ('19', 'Wrestling'), ('20', 'Other')], default='0', max_length=220),
        ),
    ]
