# Generated by Django 2.2.16 on 2020-11-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20201104_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='competition',
            field=models.CharField(choices=[('0', 'Choose Competition Level'), ('1', 'High School'), ('2', 'College'), ('3', 'Professional'), ('4', 'Recreational'), ('5', 'Other')], default='0', max_length=225),
        ),
    ]
