# Generated by Django 2.2.17 on 2020-12-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_competition'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='premium_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
