# Generated by Django 2.2.17 on 2020-12-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_premium_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='premium_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
